version: '3.7'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - /Users/dennygeorge/Documents/Tattle/playground/docker-volume:/web-data
      - /Users/dennygeorge/Documents/Tattle/playground/docker-volume/db:/db-data
      - .:/app
    command: gunicorn --worker-tmp-dir /dev/shm --workers=1 --threads=4 --worker-class=gthread --log-file=- -b 0.0.0.0:80 application:app --reload 
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: 
      - word2vec_db

  word2vec_db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true