name: CI

on: 
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish to Docker2
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tattletech/test-search-server
        username: tattlemade
        password: ${{ secrets.DOCKER_PASSWORD }}
