name: CI

on: 
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Docker
      run: |
        docker login --username tattlemade --password ${{ secrets.DOCKER_PASSWORD }} docker.io
        docker build -t search-server .
        docker tag search-server tattletech/test-search-server:latest
        docker push tattletech/test-search-server:latest
