name: CI

on: 
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!!!
    - name: Install EB-CLI
      run: pip install awsebcli --upgrade --user
    - name: verify
      run: ~/.local/bin/eb --version
    - name: deploy to ebs
      run: ~/.local/bin/eb deploy TattleSearchServer-dev -l $GITHUB_SHA
